export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCT : 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART,",
    SET_CATEGORIES_PRODUCTS: 'SET_CATEGORIES_PRODUCTS',
    AUTHORIZE_USER : 'AUTHORIZE_USER',
    NEW_USER: 'NEW_USER',
    SET_USERS: 'SET_USERS'
}